import requests
import os
import json

api_key = "YOUR_XAI_API_KEY_HERE"  # Replace with your actual API key or set as environment variable
if not api_key:
    raise ValueError("API key not found. Please set the 'XAI_API_KEY' environment variable.")

url = "https://openrouter.ai/api/v1/chat/completions"
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {api_key}",
    "HTTP-Referer": "http://localhost",
    "X-Title": "Grok Prompt Test",
}   



# Variable containing the raw test script generated by your system
generated_script = """
Your auto-generated Playwright Python test script goes here.

"""

# Variable containing Playwright Codegen interactions (recorded script)
playwright_codegen_interactions = """
# (Your Playwright codegen output here, usually in JavaScript or Python)

"""

# Prompt to refine the generated test script using codegen interactions
refine_prompt = f"""
You are an expert QA automation assistant specializing in Playwright.

Your task is to take the **auto-generated test script** below and refine it 
according to the **Playwright Codegen interactions** that follow.

1. Review the interactions through playwright codegen for the website. Go through the steps carefully and throughly.
2. Compare the codegen interactions with the auto-generated test script.
3. Fix the auto-generated test script to ensure it accurately reflects the interactions recorded by Playwright Codegen.
4. Fix the selectors in the auto-generated test script to match those used in the codegen interactions.
5. For example if any website requires redirection to another page, make sure the auto-generated test script also includes that redirection step. Match this with the codegen interactions for example Air Travel.
6. There should be no errors for waiting for elements to be visible. 
7. Maintain Playwright best practices:
   - Use `expect()` assertions where relevant.
   - Include comments for clarity (e.g., `# Step 1: Login`, `# Step 2: Navigate to Dashboard`).
   - Format cleanly and consistently using Playwright’s Python style.
   - Use to_be_visible(), to_have_text(), and other relevant expect methods for assertions.
   - Add print statements to indicate success or failure of key steps.
   - Add to_be_visible() check before interacting with each element such as clicking, filling etc.
   - Add .click() after filling input fields and also before filling if that is part of the interaction.
    - Add .press("Enter") after filling input fields if that is part of the interaction.
   - Add timeouts between steps such as search and clicking and viewing results to ensure the page has loaded.
   - Instead of adding wait_for_load_state(networkidle), use wait_for_load_state("domcontentloaded") for safe side where it requires waiting for page to load.
8. Make sure the final script is syntactically correct and ready to run. 
9. If you add any comments or explainations, make sure they are relevant and concise and they are in the form of code comments.
10. Remove ''```python``` tags if present.

---
Auto-generated test script:
{generated_script}

---
Playwright Codegen interactions:
{playwright_codegen_interactions}

---
Now produce the corrected and refined **Playwright Python test script** ready to run.
"""

# Then send `refine_prompt` to your model
data = {
    "model": "x-ai/grok-4-fast",
    "messages": [
        {"role": "system", "content": "You are a QA automation expert specializing in Playwright."},
        {"role": "user", "content": refine_prompt}
    ]
}

response = requests.post(url, headers=headers, json=data)

if response.status_code == 200:
    try:
        reply_json = response.json()
        reply = reply_json["choices"][0]["message"]["content"]
        
        output_file = "refined_test_script_app_catalogue.py"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(reply.strip())
        print(f"✅ Refined script saved successfully to: {output_file}")

    except requests.exceptions.JSONDecodeError:
        print("❌ API returned a non-JSON response. Here's the raw output:")
        print(response.text)

else:
    print(f"❌ Error {response.status_code}: {response.text}")
